apiVersion: v2
name: api-gateway
description: Apache APISIX gateway, API management bootstrap, and mock API
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: apisix
    version: "2.17.0"
    repository: "https://apache.github.io/apisix-helm-chart"
